name: QA Integration Tests

on:
  workflow_run:
    workflows: ["Store Service CI", "User Service CI"]  # must match `name:` in those repos' workflows
    types: [completed]

  schedule:
    - cron: "0 2 * * *"  # every night at 2 AM UTC

  repository_dispatch:
    types: [ store_service_updated, user_service_updated ]


jobs:
  integration-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QA tests repo
        uses: actions/checkout@v4

      - name: Log in to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login myregistry.com -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Pull staging images
        run: |
          docker pull myregistry.com/myorg/store-service:staging
          docker pull myregistry.com/myorg/user-service:staging

      - name: Run integration tests
        run: |
          docker compose -f docker-compose.staging.yml up --abort-on-container-exit --exit-code-from test-runner

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.staging.yml down -v
